### PR TITLE
chore(CI): Improved Dockerfile with mount and lints

### PR DESCRIPTION
**Pull request by AndesKrrrrrrrrrrr**
When working locally, I often have to re-build the images. This significantly speeds up subsequent builds.

In this PR:
- Build speed-up with volume caching
- Refactored copied code, to minimise the number of bytes moved around
- Linted and formatted with [hadolint](https://github.com/hadolint/hadolint)

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

## Summary by CodeRabbit

- **Refactor**
    - Enhanced CI scripts for better performance and readability.
    - Streamlined Dockerfile commands for efficiency and improved caching.
    - Improved error handling and debugging features in CI scripts.
- **New Features**
    - Added support for Podman as an alternative container tool in CI environments.
- **Documentation**
    - Updated comments in Dockerfile for clearer understanding.
- **Chores**
    - Modified user and group creation for consistency in Docker configurations.

### CODE REVIEW

**Comment by busla** [comment]
What problem are you solving? Please add a description.

**Comment by busla** [comment]
No CI jobs have run to actually test the refactored Dockerfile.

Also, it's not part of our current sprint, and requires pulling in many reviewers given the impact on all services, risking disruption.

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Comment by andes-it** [comment]
This PR closed its doors. Sat around for a day after the stale tag, then reckoned it's not worth the fuss.

**Review by AndesKrrrrrrrrrrr — COMMENTED** [review]
Self-review LGTM

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Comment by AndesKrrrrrrrrrrr** [comment]
This has become stale. The idea is good, but current resources are low and risk of disruption is great. Closing, for now

**Pull request closed without merging**
