### PR TITLE
feat(core): mask national ids from logs

### PR DESCRIPTION
**Pull request by eirikurn**
## What

Mask national ids from our logs.

## Why

To avoid logging personally identifiable information.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by saevarma — APPROVED** [review]
LGTM.
Only one question:
Is it possible that the nationalId could also be in the form: `123456 7890`?

**Comment by eirikurn** [comment]
I think that's exceedingly unlikely in logs. I'm not even sure we have a format function for that at the moment.

**Review by pshomov — APPROVED** [review]
Triple BEAM FTW 🌈 🦄

**Review by darrikonn — APPROVED** [review]
Nice

**Review by VilliGunn — APPROVED** [review]
LGTM 💯

**Pull request merged**
