### PR TITLE
fix(infra): support podman, nuke proxies util script

### PR DESCRIPTION
**Pull request by busla**
## What

[podman](https://podman.io/) support when running `_run-aws-eks-commands.js` yargs script.

## Why

Workstations that run `podman` instead of docker normally have `alias docker=podman` but the yargs script runs its own subshell.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by pshomov — APPROVED** [review]
LGTM

**Review by pshomov — APPROVED** [review]
LGTM

**Comment by busla** [comment]
@AndesKrrrrrrrrrrr I dropped this ball long time ago and you have given this topic some love lately. Could you review?

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Comment by andes-it** [comment]
This PR closed its doors. Sat around for a day after the stale tag, then reckoned it's not worth the fuss.

**Pull request closed without merging**
