### PR TITLE
chore(all): Remove all references to Gitbook

### PR DESCRIPTION
**Pull request by snaerseljan**
# Remove Gitbook

We are simplifying our documentation process by eliminating it from our monorepo. Now documentation is updated only on **Gitbook**. This way the process convenient, for all employees not only developers.

We will still continue the technical documentation in our monorepo, i.e. apps, libs etc. 

This PR removes all references to Gitbook!

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by AndesKrrrrrrrrrrr — APPROVED** [review]

**Review by saevarma — APPROVED** [review]
💯

**Comment by gzur** [comment]
> Now documentation is updated only on Gitbook. 

Is there an onboarding procedure for Gitbook somewhere?

**Comment by saevarma** [comment]
> > Now documentation is updated only on Gitbook. 
> 
> 
> 
> Is there an onboarding procedure for Gitbook somewhere?

We have qualified for a free community license on Gitbook. It includes team and account management. So those that will be contributing to our handbooks will have to be invited to Gitbook. We will post on Slack about this and then probably use the #organizational-access-changes channel to request access.

**Comment by saevarma** [comment]
Admin merged to push the removal of Gitbook to main to prevent our CI to publish changes to docs.devland.is as it is now maintained in the Gitbook platform.

**Pull request merged**
