### PR TITLE
fix(service-portal): featureflag islykill

### PR DESCRIPTION
**Pull request by thordurhhh**
## What

Hotfix for feature flag on islyklar service.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by eirikurn — DISMISSED** [review]
LGTM

**Comment by darrikonn** [comment]
Do we not want this to go to main?

and then cherry-picked?

**Review by eirikurn — APPROVED** [review]

**Comment by eirikurn** [comment]
This was supposed to be a high priority hotfix which got then stuck in CI hell. Turns out it's not a critical hotfix but still good to push out.

@thordurhhh we should generally create PRs for both main and release. Or start on main and then cherry pick to release. In this case, let's just merge this and then cherry pick it to a new PR on main.

**Comment by thordurhhh** [comment]
Yeah, normally I would had done this the other way round. 💯 
Was trying to move quickly yesterday to ship the fix.

**Review by pshomov — APPROVED** [review]
LGTM

**Review by eirikurn — APPROVED** [review]

**Pull request merged**
