### PR TITLE
chore(application-system): Move application core types to application types library

### PR DESCRIPTION
**Pull request by Thorrik58**
# Refactor application core types to application types library

Attach a link to issue if relevant

## What

Moved all types in the application/core lib to a lib on its own under application.

## Why

Types shouldnt live under the application core and were causing issues where we needed to duplicate code in order to avoid circular dependancies..

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by disaerna — APPROVED** [review]
Code owned file looks good 👍

**Review by eirikurn — APPROVED** [review]

**Review by qdd1 — APPROVED** [review]

**Review by johannaagma — APPROVED** [review]

**Review by kksteini — APPROVED** [review]
Scrolled through quickly but checked on workspace, configs and other relevant files.
Seemed to me it was the same pattern of renaming imports.
LGTM

**Review by albinagu — APPROVED** [review]
👏

**Review by HelgiHH — APPROVED** [review]
LGTM

**Pull request merged**
