### PR TITLE
Markdown spelling

### PR DESCRIPTION
**Pull request by AlexanderFL**
# \<Description\>

Niche formatting and spelling changes in markdown files

## What

- Better symmetry in wording
- Changed wording of certain sentences
- Capitalization of certain words
- Commas in lists

## Why

- Makes the overall symmetry in markdown files better

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against master before asking for a review

### CODE REVIEW

**Review by darrikonn — DISMISSED** [review]

**Comment by jeremybarbet** [comment]
Hey @AlexanderFL,

Could you rebase your changes with main? Also, your changes were failing on the CI because of formatting. Could you run `yarn nx format:write` to fix that?

**Comment by jeremybarbet** [comment]
I should have say merge and not rebase. Could you merge main into your branch? So we won't get all the others changes in your PR?

**Comment by AlexanderFL** [comment]
No problem, should be good now?

**Comment by jeremybarbet** [comment]
Looks good now, thanks!

**Review by jeremybarbet — APPROVED** [review]

**Review by oddsson — APPROVED** [review]

**Review by darrikonn — APPROVED** [review]

**Pull request merged**
