### PR TITLE
Feature/thjonustusidur markdown

### PR DESCRIPTION
**Pull request by stullifugl**
# \<Description\>

Attach a link to issue if relevant

## What

Adding to gitbook thjonustusidur for the island.is authentication system

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

### CODE REVIEW

**Comment by stullifugl** [comment]
Jéremy Barbet´s pull request has not been accepted when I write this comment. 
https://github.com/island-is/island.is/pull/2704 

It stops me from being able to run yarn gitbook correctly on my windows computer. 
If someone could accept the pull or run yarn gitbook for me that would be great

**Review by sindrig — CHANGES_REQUESTED** [review]
Woah. 102 file changes. Why moving all this around?

Also, all documentation in this repo should be in English: https://github.com/island-is/island.is/blob/b66fb9a0db386789258ff1adf7ec7193dc9cd854/handbook/technical-overview/code-standards.md#language

**Comment by stullifugl** [comment]
> Woah. 102 file changes. Why moving all this around?
> 
> Also, all documentation in this repo should be in English: https://github.com/island-is/island.is/blob/b66fb9a0db386789258ff1adf7ec7193dc9cd854/handbook/technical-overview/code-standards.md#language

Yeah sorry about all the file changes. 
It´s basically taking a handbook written in word, converting it to markdown and adding it into gitbook. 
This is a request from @vigfusg. 

We also took the chat a while ago regarding languages and it was decided to have them in Icelandic. 
So @vigfusg has to have some input what the next steps regarding the code-standards should be. 

Autolabel is not set on this pull request because it should not be merged until Vigfús gives the thumbs up.

**Comment by vigfusg** [comment]
> > Woah. 102 file changes. Why moving all this around?
> > Also, all documentation in this repo should be in English: https://github.com/island-is/island.is/blob/b66fb9a0db386789258ff1adf7ec7193dc9cd854/handbook/technical-overview/code-standards.md#language
> 
> Yeah sorry about all the file changes.
> It´s basically taking a handbook written in word, converting it to markdown and adding it into gitbook.
> This is a request from @vigfusg.
> 
> We also took the chat a while ago regarding languages and it was decided to have them in Icelandic.
> So @vigfusg has to have some input what the next steps regarding the code-standards should be.
> 
> Autolabel is not set on this pull request because it should not be merged until Vigfús gives the thumbs up.

Yes, the language is unfortunate. Originally this contect was supposed to be directly on island.is but was to extensive and technical for that. Therefore the icelandic text. We have run out of time to remedy that for now :(

**Comment by stullifugl** [comment]
> > > Woah. 102 file changes. Why moving all this around?
> > > Also, all documentation in this repo should be in English: https://github.com/island-is/island.is/blob/b66fb9a0db386789258ff1adf7ec7193dc9cd854/handbook/technical-overview/code-standards.md#language
> > 
> > 
> > Yeah sorry about all the file changes.
> > It´s basically taking a handbook written in word, converting it to markdown and adding it into gitbook.
> > This is a request from @vigfusg.
> > We also took the chat a while ago regarding languages and it was decided to have them in Icelandic.
> > So @vigfusg has to have some input what the next steps regarding the code-standards should be.
> > Autolabel is not set on this pull request because it should not be merged until Vigfús gives the thumbs up.
> 
> Yes, the language is unfortunate. Originally this contect was supposed to be directly on island.is but was to extensive and technical for that. Therefore the icelandic text. We have run out of time to remedy that for now :(

After a talk with Vigfús it has been decided that the icelandic version will be moved somewhere else. This text will be translated to English later on and will then be added

**Pull request closed without merging**
