### PR TITLE
feat(smart-solutions-v2): new smart solutions v2 client

### PR DESCRIPTION
**Pull request by thorkellmani**
## What

* new smart solutions client with updated config and error handling
* Uses apollo client instead of manual fetches

## Why

The previous iteration was too manual with cluttered error handling

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

## Summary by CodeRabbit

- **New Features**
	- Enhanced Smart Solutions V2 client library with pass verification, updating, generation, and revocation functionalities.
	- Integrated Apollo Client for GraphQL operations to interact with pass data dynamically.
	
- **Documentation**
	- Updated documentation with detailed information on new pass management features and GraphQL usage.
	
- **Tests**
	- Implemented Jest for unit testing to ensure the reliability of pass management functions.
	
- **Chores**
	- Set up linting, testing, and code generation configurations for improved code quality and development processes.

### CODE REVIEW

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Comment by thorkellmani** [comment]
Would appreciate some notes on Apollo client set-up best practices

**Review by AndesKrrrrrrrrrrr — APPROVED** [review]
CODEOWNERS LGTM

**Comment by saevarma** [comment]
I talked to Eiki about this to compare this method to what we supported Deloitte to do in 
https://github.com/island-is/island.is/tree/main/libs/clients/car-recycling

In short:  we used codegen to generate types so we can have typesafety but then using enhancedFetch to do the requests.

We are scared of using ApolloClient server side due to it potentially leaking memory and the cache might run the server out of memory. That library is also heavily optimised for client side functionality so it introduces a lot of overhead that we don´t need in a server side client.

You could look into [GraphQLClient](https://github.com/jasonkuhrt/graphql-request/tree/main) combined with the near-operation-file type generation and use the GraphQLClient custom fetch support, where we could use our enhancedFetch.  Or take a similar route to the car-recycling client.

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Pull request closed without merging**
