### PR TITLE
More content types in search results

### PR DESCRIPTION
**Pull request by stefanhar**
# New types in search results

## What

- Added more types to search results.
- Made search input user reducer to simplify state management
- Made search input not wait for roundtrip before making next request
- Reduced debounce time

## Why

We want to find more stuff

## Screenshots / Gifs

Screenshot 2020-09-19 at 18 57 08
Screenshot 2020-09-20 at 09 12 55
Screenshot 2020-09-20 at 09 12 59
Screenshot 2020-09-20 at 09 13 08

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Formatting passes locally with my changes
- [x] I have rebased against master before asking for a review

### CODE REVIEW

**Review by maggisk — DISMISSED** [review]

**Review by haukurh — CHANGES_REQUESTED** [review]
Dosen't work, get this error constantly, did re-sync for search engine and the error still persists (and even if the data from ES were of it shouldn't take down the site)...
Works fine on master
image

**Comment by stefanhar** [comment]
> Dosen't work, get this error constantly, did re-sync for search engine and the error still persists (and even if the data from ES were of it shouldn't take down the site)...
> Works fine on master
> image

This error is not related to this PR, the fix for this error has been merged into master.
I rebased, this code should work as expected now

**Review by haukurh — COMMENTED** [review]
I get no data to import for about page, has that been tested ?

**Comment by stefanhar** [comment]
> I get no data to import for about page, has that been tested ?

I wrongly assumed this was caused by lack of valid data.
I updated the code to address this issue

**Review by haukurh — DISMISSED** [review]

**Review by haukurh — APPROVED** [review]

**Pull request merged**
