### PR TITLE
Feature/dummy test

### PR DESCRIPTION
**Pull request by unnarb**
#Altering fields to non nullable and adding a temporary dummy test since it runs into unknown problems

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

### CODE REVIEW

**Review by valurefugl — APPROVED** [review]

**Review by dabbeg — COMMENTED** [review]
I don't understand the reasons for commenting out all these tests, can you clarify that?

**Comment by unnarb** [comment]
> I don't understand the reasons for commenting out all these tests, can you clarify that?

A seed file, setting all values for new delegation fields to false, ran on the dev db. We wanted to change the fields to NOT NULL since it is in the same structures as other Boolean fields in the table. The test fails and the only logical reason for that, we feel, is that it is running these tests to a temporary db, that the build pipeline builds. Something is wrong in that pipeline. The test should be fine if the db in the build flow is setup correctly. We don't know the solution to that problem

**Comment by dabbeg** [comment]
> > I don't understand the reasons for commenting out all these tests, can you clarify that?
> 
> A seed file, setting all values for new delegation fields to false, ran on the dev db. We wanted to change the fields to NOT NULL since it is in the same structures as other Boolean fields in the table. The test fails and the only logical reason for that, we feel, is that it is running these tests to a temporary db, that the build pipeline builds. Something is wrong in that pipeline. The test should be fine if the db in the build flow is setup correctly. We don't know the solution to that problem

If I remember correctly the test database runs a code first migration with the sequelize models. Did you change the Sequelize models to be notnull as well?

**Comment by unnarb** [comment]
> > > I don't understand the reasons for commenting out all these tests, can you clarify that?
> > 
> > 
> > A seed file, setting all values for new delegation fields to false, ran on the dev db. We wanted to change the fields to NOT NULL since it is in the same structures as other Boolean fields in the table. The test fails and the only logical reason for that, we feel, is that it is running these tests to a temporary db, that the build pipeline builds. Something is wrong in that pipeline. The test should be fine if the db in the build flow is setup correctly. We don't know the solution to that problem
> 
> If I remember correctly the test database runs a code first migration with the sequelize models. Did you change the Sequelize models to be notnull as well?

AHA... ok, that's the reason. We were going to do this in separate PR. Thank you

**Review by dabbeg — APPROVED** [review]

**Pull request merged**
