### PR TITLE
chore(core): Upgrade PostgreSQL from 11.14 to 15.3

### PR DESCRIPTION
**Pull request by eirikurn**
## What

Upgrade version of PostgreSQL used ƒor local development and CI.

This is the first step in our [upgrade plan](https://www.notion.so/Upgrade-Postgres-to-15-3-c5913fb32aa44e119608ce09c5b3b842?pvs=4).

## Why

Because we're 3 majors out of date and version 11 is not supported anymore (since Nov 9, 2023).

## Checklist:

- [x] Make sure CI (and all API tests) pass.
- [x] Test local development with 1-2 services.
- [ ] Merge

See the [upgrade plan](https://www.notion.so/Upgrade-Postgres-to-15-3-c5913fb32aa44e119608ce09c5b3b842?pvs=4) for next steps.

### CODE REVIEW

**Comment by eirikurn** [comment]
Manually tested local ids db through services-auth-delegation-api, including migrations and seeds. Worked like a charm.

Main gotcha is that developers will have to remove their old docker databases or manually run pg_upgrade somehow.

**Review by saevarma — APPROVED** [review]
🫙

**Review by gudjong — APPROVED** [review]

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Pull request merged**
