### PR TITLE
chore(service-portal): Add health overview scope

### PR DESCRIPTION
**Pull request by thordurhhh**
## What

* Add rights-status scope for health overview.

## Why

Currently there's no specific scope for health overview.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by thorkellmani — APPROVED** [review]
LGTM

**Review by saevarma — APPROVED** [review]
Has this scoped been created in all IDS environment or should it be added to this PR as a migration script?

**Comment by thordurhhh** [comment]
> Has this scoped been created in all IDS environment or should it be added to this PR as a migration script?

Are we back to doing migration scripts? It has only been added to dev. I can definitely add this with a migration script.

**Comment by saevarma** [comment]
> > Has this scoped been created in all IDS environment or should it be added to this PR as a migration script?
> 
> Are we back to doing migration scripts? It has only been added to dev. I can definitely add this with a migration script.

@jonarnarbriem did we stop recommending migration scripts for island.is scopes? 
I have preferred them as then they will always be created along with the deployed code requiring them.

**Pull request merged**
