### PR TITLE
build: fix openapi attribute injection race condition

### PR DESCRIPTION
**Pull request by busla**
# Reported on Slack

https://islandis.slack.com/archives/C019LNRM6LE/p1655815725049899

https://islandis.slack.com/archives/C019VN1KG04/p1657190936765069

## What
`yarn install` fails with the following error

```bash
 >  NX   Running target "schemas/external-openapi-generator" failed

   Failed tasks:
   
   - clients-vehicles:schemas/external-openapi-generator
```

## Why

The NX update-openapi-document command is writing json strings to a _.tmp file and reads the same file to update clientConfig.json. This change will remove the I/O read operation and feeds the string to stdin for cat to update the file.

If NX is running commands in parallel all commands are writing to the same `._tmp` file.

So instead of this:
```bash
jq '.components.schemas.ProblemDetails.additionalProperties = false' src/clientConfig.json > _.tmp && mv _.tmp src/clientConfig.json
```

We do this
```bash
cat <<< $(jq '.components.schemas.ProblemDetails.additionalProperties = false' src/clientConfig.json) > src/clientConfig.json
```
## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by kristofer-lp8f — APPROVED** [review]
LGTM :+1:

**Review by saevarma — APPROVED** [review]
LGTM

**Review by disaerna — APPROVED** [review]
LGTM 🚀

**Review by RunarVestmann — APPROVED** [review]

**Review by Thorrik58 — APPROVED** [review]
Lgtm

**Pull request merged**
