### PR TITLE
refactor(web): anchor page

### PR DESCRIPTION
**Pull request by splicebison**
# Refactor Anchor Page content

‼️ - this requires a migration script to be run against Contentful `master` when the code is ready to release. The scripts have been tested thoroughly in a sandbox environment however this will require the indexer to be fully re-synced. 

## What

The Anchor Page type was previously called Life Event Page. When it was renamed to Anchor Page, the system architecture was never updated to match. Because of this, all the code references and contentful id still read as `lifeEventPage`.

## Why

Part of the web ux 2.0 changes will see Life Events separated from the traditional Anchor Page as it currently stands. Anchor Page will continue to live on and evolve for other use-cases. In order to refactor the Life Event entry type, we need to provide a new (correct) entry type for Anchor Page. This will be a migration effort in two parts. First, the codebase needs to correctly reference and use the `anchorPage` entry type. This will require the current content to be duplicated over to the new content type. After, we can separate Life Events from the Anchor Page.

This allows us to work on this simultaneously without affecting the live data and the current Anchor Pages. Once the new Anchor Page rolls out in a release, we can remove the old Anchor Page content and start the refactor process of Life Events Page.

> To run locally with migrated data, set `CONTENTFUL_ENVIRONMENT='anchorPageMigration'` and use local search indexer.

## Affected

- Contentful app sidebar (added preview to new content type)
- `apps/web`
- `libs/api`
- `libs/cms`

## Affect content

- Frontpage
- Generic Overview Page -> life events
- Menu Link
- Menu Link with Children
- Anchor Page (previously lifeEventPage)
- Anchor Page Slice
- Organization Page
- Organization Subpage
- Site Search

Currently, lifeEventPage will be migrate to anchorPage. lifeEventPageListSlice will migrate to anchorPageList. The rest of the linked entities will be updated automatically with the migration script.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by albinagu — APPROVED** [review]
júní owned stuff lgtm

**Comment by splicebison** [comment]
Screen shots of affected areas using the `anchorPageMigration` environment.

Screenshot 2023-11-27 at 15 17 18

Screenshot 2023-11-27 at 15 21 41

Screenshot 2023-11-27 at 15 21 59

Screenshot 2023-11-27 at 15 22 29

Screenshot 2023-11-27 at 15 23 08

Screenshot 2023-11-27 at 15 23 32

Screenshot 2023-11-27 at 15 24 50

**Review by RunarVestmann — APPROVED** [review]
Approved, you can go ahead and migrate everything over to the master environment in the CMS. Let's test this puppy out on dev and staging.

**Review by saevarma — APPROVED** [review]
Core files LGTM

**Pull request merged**
