### PR TITLE
chore: Module Registration Cleanup

### PR DESCRIPTION
**Pull request by gudjong**
# Module Registration Cleanup

## What

Use module-register-import pattern instead of service-options-provider pattern for service libraries.

## Why

The module-register-import pattern is better.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by oddsson — APPROVED** [review]

**Review by eirikurn — APPROVED** [review]
Nice! ❤️

**Review by obmagnusson — APPROVED** [review]
Awesome!

**Review by VilliGunn — APPROVED** [review]
💯

**Review by dabbeg — APPROVED** [review]
Nice!

**Pull request merged**
