### PR TITLE
feat(web): Organization pages, external script support

### PR DESCRIPTION
**Pull request by RunarVestmann**
# Organization pages, external script support

## What

* Added a way for organization pages to load an external script

## Why

* This was a requested feature

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by Ingimarsson — APPROVED** [review]

**Comment by kksteini** [comment]
I am worried about this.
Who requested this and for what purposes?
How will this be moderated?

I think we should take issue with allowing any script to be loaded on the basis of tracking.
As far as I know we do not track personal information across our website. We are using plausible for anonymous heatmap and query tracking purposes. There is no "Allow Cookies" banner on island.is for example.

**Comment by kksteini** [comment]
Also, will this not clash with the viewer-response ruleset, see here: https://github.com/island-is/infrastructure/blob/main/modules/islandis-cloudfront/viewer-response.js?

**Comment by RunarVestmann** [comment]
This was requested by Sjúkratryggingar originally. They want to embed a script that allows the web to automatically show if there is an error for one of their web services. So basically the script shows a pop up in the bottom right corner if it is appropriate. And regarding the viewer-response ruleset, I believe that Snorri from Andes changed the ruleset for this as he was also in the e-mail communication regarding this.

**Comment by RunarVestmann** [comment]
Alright, let's put this on hold for now, I might be going for another solution to solve this issue: https://islandis.slack.com/archives/C02P06N03T3/p1658395848757129

**Pull request closed without merging**
