### PR TITLE
fix(ci): Force quotes in yaml

### PR DESCRIPTION
**Pull request by sindrig**
Since some developers get quotes when generating chart values,
force quotes on everything for consistency.

### CODE REVIEW

**Review by eirikurn — APPROVED** [review]

**Review by pshomov — APPROVED** [review]
LGTM

**Comment by eirikurn** [comment]
@sindrig get this merged?

**Comment by sindrig** [comment]
> @sindrig get this merged?

Yep thought I had automerge on it. Should go through now!

**Comment by eirikurn** [comment]
@sindrig this PR breaks almost all usage of js-yaml in our repo since they removed all `safe*` functions in 4.0.0. There's a migration guide and everything.

https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md

TypeScript didn't catch this issue because we only have unofficial type definitions (`@types/js-yaml`) which this PR forgot to upgrade from v3 to v4.

It should be pretty easy to fix all references, but I can't get to it until Monday. Your call if you want to revert this first.

**Comment by sindrig** [comment]
This change is in no way critical, but it's possibly breaking our chances of reacting quickly to issues. I vote we revert and take another look at this on Monday. See #5041

**Pull request merged**
