### PR TITLE
feat(auth-api-lib): index delegations

### PR DESCRIPTION
**Pull request by Herdismaria**
[Index delegations](https://www.notion.so/Index-delegations-in-IncomingDelegationService-getAllAvailable-ba6464115f4344839ab8e17e5fbe0e7a?pvs=4)
## What
Implement `indexDelegation` method in `DelegationIndexService` that finds all delegations to the authenticated user and saves them to the delegation index table.

## Why
Store delegations in our database to limit number of requests to third party services to fetch delegations.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by GunnlaugurG — APPROVED** [review]
LGTM, great job!

**Review by GunnlaugurG — APPROVED** [review]
LGTM, great job!

**Review by eirikurn — APPROVED** [review]
Approving core files 👍

**Review by baering — APPROVED** [review]
LGTM ✅

**Pull request merged**
