### PR TITLE
feat(ci): adding db undo script

### PR DESCRIPTION
**Pull request by Snojo**
# ...
This is untested and still a WIP 
A script for undoing all migrations in a release

This doesn't currently work. We need to make it go into each sequilize directory and init. 
We also need the DB connection along with ENV configs

fixes: https://github.com/island-is/island.is/issues/7060

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

### CODE REVIEW

**Comment by saevarma** [comment]
Change it to a Draft PR until it's ready?

**Comment by saevarma** [comment]
@Snojo what is the status of this PR?

**Comment by Snojo** [comment]
@saevarma We realized that this is a bit more complicated than we expected.
We need to take another look at it, and it's in the backlog, but we haven't touched it in a while

**Comment by saevarma** [comment]
@island-is/devops time to close this?

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Comment by andes-it** [comment]
This PR closed its doors. Sat around for a day after the stale tag, then reckoned it's not worth the fuss.

**Pull request closed without merging**
