### PR TITLE
feat(native-app): Implement universal links

### PR DESCRIPTION
**Pull request by eirikurn**
- Only runs when the user is logged in and has passed the pin screen.
- Improves notification handling to support passkey browser.

## Summary by CodeRabbit

- **New Features**
	- Introduced support for Universal Links, enhancing navigation to specific content within the app.
	- Added deep link handling capabilities to improve user experience when responding to notifications and links.
  
- **Enhancements**
	- Updated navigation functionality to allow links to be opened in a browser or within the app.
	- Improved organization of dependencies and hooks in various components for better maintainability.

- **Bug Fixes**
	- Streamlined event handling by removing unnecessary logging and checks for URL processing.

### CODE REVIEW

**Review by saevarma — APPROVED** [review]
Core files LGTM

**Review by thoreyjona — APPROVED** [review]
Nice! I think it would be good to also get review from @snaerseljan, since he has done most of the work on these files that you are changing. 
I did not test it, only read over the code 👀

**Review by snaerseljan — APPROVED** [review]
LGTM! Nice work! Tested on Android and Ios?

**Comment by eirikurn** [comment]
Tested on iOS. Didn't have an Android phone. Will test with internal testing.

**Pull request merged**
