### PR TITLE
chore: Describe how to enable read replicas

### PR DESCRIPTION
**Pull request by dabbeg**
https://github.com/island-is/infrastructure/issues/1130

## What

Writing up instructions on how to enable read replicas. Additionally I refactored all services that use sequelize get their config from a single library.

## Why

So developers can enable read replicas for their service without help and to make that process simpler I refactored the config.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by darrikonn — APPROVED** [review]
Nice

**Review by Valur — APPROVED** [review]

**Review by Snojo — APPROVED** [review]

**Review by pshomov — APPROVED** [review]
LGTM

**Review by Rikkiabb — APPROVED** [review]
👏 👏 👏

**Pull request merged**
