### PR TITLE
build(all): better caching for assets in static-rendered apps

### LINKED ISSUE #3314: Configure caching headers for static apps
Our static apps are hosted in an nginx container which has no cache control set. The [default behaviour](https://webmasters.stackexchange.com/questions/111298/what-happens-if-you-dont-set-cache-control-header) will cause issues.

For index.html requests, we should set something like `cache-control: public, max-age=0`

For most other requests, we should set something like `cache-control: public, max-age=31536000`.

My only concern are favicon and some static files in the /assets folder which are not versioned currently.

Ideally, if we can detect requests that have `/\.[0-9a-f]{20}\./` hashes in their filename. we can safely configure far future caching with `immutable` (`cache-control: public, max-age=31536000, immutable`), which skips revalidation requests even on page refresh.

### PR DESCRIPTION
**Pull request by pshomov**
# \<Description\>

Fixes #3314

## What

Cache in the browser more assets than fewer

## Why

We like things snappy

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

### CODE REVIEW

**Review by eirikurn — COMMENTED** [review]
This looks like a great fix for static file caching, but we also need to disable caching for all index.html paths, somehow.

**Comment by pshomov** [comment]
Yes, was just interested in the webpack assets section only at the time. Now added the explicit cache control for the routes as well.

**Review by eirikurn — APPROVED** [review]
Sweet!!

**Review by sindrig — APPROVED** [review]
LGTM

**Pull request merged**
