### PR TITLE
feat: storybook escape grid util

### PR DESCRIPTION
**Pull request by jeremybarbet**
## What

- Create style util function to escape grid gutters.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against master before asking for a review

### CODE REVIEW

**Review by atligudl — APPROVED** [review]
Will create a PR to handle the potentially unsafe warning

**Comment by jeremybarbet** [comment]
Surprisingly enough, I didn't touch the file where the warning is emitted from 🤔

**Review by arnifreyrs — DISMISSED** [review]

**Comment by jeremybarbet** [comment]
I couldn't import `escapeGrid` when it was located inside `libs/island-ui/core`. When running `yarn start web`, `treat-webpack-plugin` was complaining with a 

Screenshot 2020-10-21 at 12 42 13.

I couldn't figure it out why, so I moved the util function to `libs/island-ui/theme` and it works. If anyone knows what's wrong?

**Review by DavidBachmann — APPROVED** [review]
LGTM

**Review by arnifreyrs — APPROVED** [review]

**Pull request merged**
