### PR TITLE
island-ui / Deprecate old Icon

### PR DESCRIPTION
**Pull request by barabrian**
# \<Description\>

Deprecating old icon and importing new iconRC as Icon

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against master before asking for a review

### CODE REVIEW

**Review by oddsson — DISMISSED** [review]

**Review by DavidBachmann — APPROVED** [review]

**Review by sindrig — APPROVED** [review]

**Review by darrikonn — APPROVED** [review]
Like a glove!

**Review by siggakogk — APPROVED** [review]
Nice!

**Review by DavidBachmann — APPROVED** [review]
👍

**Review by oddsson — APPROVED** [review]

**Review by obmagnusson — APPROVED** [review]
LGTM

**Pull request merged**
