### PR TITLE
refactor(ci): refactoring the script a bit to bring more clarity

### PR DESCRIPTION
**Pull request by pshomov**
# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

### CODE REVIEW

**Review by dabbeg — COMMENTED** [review]
Can you add a some instructions on how to test this out locally?

**Comment by pshomov** [comment]
> Can you add a some instructions on how to test this out locally?

The [README](.github/actions/README.md) says it all: `yarn` and `yarn test`. Or do you maybe have something else in mind?

**Comment by dabbeg** [comment]
> > Can you add a some instructions on how to test this out locally?
> 
> The [README](.github/actions/README.md) says it all: `yarn` and `yarn test`. Or do you maybe have something else in mind?

In `main.ts` there is a comment
```
For local development
{
  auth: process.env.GITHUB_TOKEN
}
```

But the readme doesn't mention what this token is and how to run the local development

**Review by dabbeg — APPROVED** [review]
Awesome!

**Pull request merged**
