### PR TITLE
chore: build and schemas scripts fixes

### PR DESCRIPTION
**Pull request by jeremybarbet**
## What

- Fix broken build with updated input dto
- Update resolvers passed to the buildSchema resolver array
- Remove contentful-types command from yarn schemas. Already discussed before, but I forgot to remove it from previous changes. The command should be run only by people touching contentful models.
- Fix typo in command name in nx.json

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against master before asking for a review

### CODE REVIEW

**Review by arnifreyrs — APPROVED** [review]

**Comment by jeremybarbet** [comment]
For people working on Adgerðir @island-is/kosmos-kaos I had to do something dirty to be able to run `yarn build adgerdir`. If anyone knows what's going on:

```
content: Array<Slice>

export type Slice =
  | TimelineSlice
  | MailingListSignupSlice
  | HeadingSlice
  | ...
```

Screenshot 2020-11-12 at 12 35 25

**Review by oddsson — DISMISSED** [review]

**Review by arnifreyrs — APPROVED** [review]

**Review by barabrian — APPROVED** [review]
lgtm

**Review by dabbeg — APPROVED** [review]
:+1:

**Review by essgje — APPROVED** [review]
lftm

**Review by pshomov — APPROVED** [review]

**Review by oddsson — APPROVED** [review]

**Pull request merged**
