### PR TITLE
docs: Pósthólf documentation fix 

### PR DESCRIPTION
**Pull request by valsarinn**
### What
Converted the opening page (getting started section) in the Pósthólf documentation from Icelandic to English.  

### Checklist:
 

- [x] I have performed a self-review of my own code
- [x]  I have made corresponding changes to the documentation
- [x]  My changes generate no new warnings
- [ ]  I have added tests that prove my fix is effective or that my feature works
- [x]  Formatting passes locally with my changes
- [ ]  I have rebased against main before asking for a review

### CODE REVIEW

**Comment by GunnarIngiReykjalin** [comment]
@island-is/core Can you provide your review?

**Review by saevarma — APPROVED** [review]
Just minor text improvements.
Feel free to add the `automerge` label when you have addressed those.

**Comment by saevarma** [comment]
> @island-is/core Can you provide your review?

Sorry for late response. Done ✅

**Comment by saevarma** [comment]
@valsarinn can you resolve the conflict so we can complete merging this.

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Comment by andes-it** [comment]
This PR closed its doors. Sat around for a day after the stale tag, then reckoned it's not worth the fuss.

**Pull request closed without merging**
