### PR TITLE
feat(auth-admin-web): Misc minor changes

### PR DESCRIPTION
**Pull request by valurefugl**
# ...

Attach a link to issue if relevant

https://www.notion.so/Small-changes-to-admin-UI-a8dc3cc314c640e198707916b2ead65f
https://www.notion.so/Hide-archived-items-in-lists-in-Admin-UI-b23e927aa4074f1e977f7ac2ba4d0641
https://www.notion.so/order-secrets-by-date-a471d4952b224a05ae88f85ff5b6c84d

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

### CODE REVIEW

**Review by saevarma — CHANGES_REQUESTED** [review]
I think we should rather let the API filter out the archived items, instead of returning them to the UI just to be filtered out.

**Comment by valurefugl** [comment]
Yeah, you're probably right. Don't you think we should have the option of requesting archived items also though? If we want to enable viewing them/undelete from the ui?

**Comment by saevarma** [comment]
> Yeah, you're probably right. Don't you think we should have the option of requesting archived items also though? If we want to enable viewing them/undelete from the ui?

Yes that would be good, provided via some query parameter.

**Review by saevarma — APPROVED** [review]
LGTM

**Review by unnarb — APPROVED** [review]

**Pull request merged**
