### PR TITLE
feat(devx): Allow multiple projects and --reset anywhere

### PR DESCRIPTION
**Pull request by kristofer-lp8f**
## What

Improve developer experience
- Allow fetching multiple project secrets in a single invocation
- Allow `--reset` option anywhere, not just at the end
- Add `-r` shortform for `--reset`
- Feedback when no secrets found
- Feedback on total number of secrets found

## Why

When interacting with the `get-secrets` command developers need to manually verify that they found _any_ secrets. There was no feedback at all; whether typo, incorrect usage, trying to use multiple projects.

## Screenshots / Gifs

Example invocation
Screenshot 2022-07-26 at 17 07 08

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by busla — COMMENTED** [review]
Personally I would like to discontinue the persistent .env.secrets file with creds in plain text, and instead export them pre-runtime to the corresponding environments.

**Comment by busla** [comment]
something like this (not tested)

```bash
function secret() {
  local param
  param="$1"

  # We split the ssm key on / and keep the last item as ENV
  aws ssm get-parameter \
    --name "$param" \
    --with-decryption \
    --query 'Parameter.{Name:Name,Value:Value}' | jq -r '. | "\(.Name|split("/")|.[-1])=\(.Value)"'
}

function set_secrets() {
  while read -r line ; do
    info "getting ${line?} from ssm and setting env"
    export "$(secret "${line?}")"
  done < "${SCRIPT_DIR}/../.env.ssm"
}

```

This approach assumes that all projects would need a `.env.ssm` file with required ssm keys for that project only. The DSL could generate those files.
 
```bash
/project/a/ENV_FOR_A
/project/a/ANOTHER_ENV_FOR_A
```

**Comment by kristofer-lp8f** [comment]
I agree that storing secrets in plaintext is bad.

Until we get proper dependency startup and something similar to what you propose, can we add this, at least until we deprecate the `get-secrets` script?

**Review by busla — APPROVED** [review]
LGTM

**Review by pshomov — APPROVED** [review]
LGTM

**Pull request merged**
