### PR TITLE
Search engine code owners

### PR DESCRIPTION
**Pull request by stefanhar**
# Search engine code owners

Updating search engine code owners

## What

Ease the development progress

## Why

We are having hard time getting reviews

## Checklist:

- [ x] I have performed a self-review of my own code
- [ -] I have commented my code, particularly in hard-to-understand areas
- [ -] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ -] I have added tests that prove my fix is effective or that my feature works
- [ -] Formatting passes locally with my changes
- [ -] I have rebased against master before asking for a review

### CODE REVIEW

**Review by arnifreyrs — DISMISSED** [review]

**Comment by eirikurn** [comment]
Last line that matches a file rules, so duplicate patterns doesn't work.

Please add your team to the stefna lines as well.

**Review by eirikurn — CHANGES_REQUESTED** [review]
See comment above

**Comment by eirikurn** [comment]
Maybe add a comment about this behaviour.

```
# Order is important; the last matching pattern takes the most
# precedence.
```

**Review by eirikurn — APPROVED** [review]

**Review by eirikurn — APPROVED** [review]
Thanks!

**Review by eirikurn — APPROVED** [review]

**Pull request merged**
