### PR TITLE
chore(gitbook): Cleanup navigation

### PR DESCRIPTION
**Pull request by eirikurn**
## What

* Allow app/lib README to have a separate document title from the navigation title.
* Rename nested navigation titles to not contain name of parent folder.
* Ignore api-domain, application-template and service-portal submodule libs.

## Why

To make out gitbook navigation nicer. Instead of a navigation like this:

```
Nest
- Nest Config Module
- Nest Feature Flag Module
```

It's something like this:

```
Nest
- Config Module
- Feature Flag Module
```

The README title should still have the full name to provide good context to users that deep link to the documentation.

Also, our gitbook should focus on providing high-level documentation for our apps and shared libraries. Most "App" submodules don't have a README, and there are so many of them that they clutter up the Gitbook navigation. So they are not available anymore in gitbook, but devs can still explore them in the codebase, on demand.

Currently these modules are manually "ignored". In a future PR it would be nice to automatically ignore specific subtrees, but  we might still want to include some of these, like service portal core? We could do this with `<!-- gitbook-include -->`, or just move all the service-portal libs we don't need into a subfolder which we can ignore, like "libs/service-portal/modules".

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] ~I have added tests that prove my fix is effective or that my feature works~
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Comment by eirikurn** [comment]
Reviewer hint: Focus on `SUMMARY.md` and `gitbook.js`.

**Review by darrikonn — APPROVED** [review]
LGTM

**Review by Rikkiabb — APPROVED** [review]
🥇

**Review by disaerna — APPROVED** [review]
👍

**Pull request merged**
