### PR TITLE
Service portal/update icons

### PR DESCRIPTION
**Pull request by atligudl**
# \<Update Service Portal Icons\>

## What

Replace deprecated icon component with new RcIcon in Service Portal app and libs

**Extra work:**
Add memoization and placeholder to RcIcon ui-core component

## Why

Update UI to follow design on icons

## Screenshots / Gifs

2020-10-16 09_25_55-Window
2020-10-16 09_26_11-Window

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [ ] I have rebased against master before asking for a review

### CODE REVIEW

**Review by barabrian — DISMISSED** [review]
very nice! LGTM

**Review by obmagnusson — DISMISSED** [review]
lgtm

**Review by barabrian — APPROVED** [review]

**Review by Thorrik58 — APPROVED** [review]
LGTM

**Review by obmagnusson — APPROVED** [review]
LGTM

**Pull request merged**
