### PR TITLE
chore(core): alphabetical sort for jest.config.js projects

### PR DESCRIPTION
**Pull request by jeremybarbet**
## What

- Follow the same alphabetical sort as nx/workspace/tsconfig files

### CODE REVIEW

**Review by eirikurn — APPROVED** [review]
Oh wow, nice job 🤗

**Review by pshomov — APPROVED** [review]
lgtm

**Review by busla — APPROVED** [review]
LGTM

**Review by darrikonn — APPROVED** [review]
Nice

**Pull request merged**
