### PR TITLE
Website / Allow articles to be shown in other categories

### PR DESCRIPTION
**Pull request by stjanilofts**
## Description

This allows for articles to be visible in categories/groups/subgroups other than their default ones. Also adds importance field to groups for sorting.

## Why

It is a feature request from the content administrators.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against master before asking for a review

### CODE REVIEW

**Review by DavidBachmann — DISMISSED** [review]
LGTM

**Review by DavidBachmann — APPROVED** [review]

**Comment by stefanhar** [comment]
Why are we creating otherCategory and otherGroup, could we maybe change category and group to multiple reference and handle this as arrays?

**Comment by stjanilofts** [comment]
> Why are we creating otherCategory and otherGroup, could we maybe change category and group to multiple reference and handle this as arrays?

**Comment by stefanhar** [comment]
> We could but then we have no default category/group/subgroup to show in the breadcrumbs of the article.

Any reason why we cant just show the first?

**Comment by stjanilofts** [comment]
> > We could but then we have no default category/group/subgroup to show in the breadcrumbs of the article.
> 
> Any reason why we cant just show the first?

For example if the article is in 2 or more categories but also in 2 or more groups, then both of those groups will show up in both of those categories. The way it works now is, it will only show up in those "other" categories/groups/subgroups if they already are being displayed by other articles that have those groups as their main/default groups.

**Review by haukurh — APPROVED** [review]
LGTM

**Pull request merged**
