### PR TITLE
style: added run-psql.sh script for SQL queries

### PR DESCRIPTION
**Pull request by busla**
# ...

Attach a link to issue if relevant

## What

Specify what you're trying to achieve

## Why

Specify why you need to achieve this

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

### CODE REVIEW

**Review by arnorhs — COMMENTED** [review]
My bash is rusty, but this seems all pretty reasonable.

Did you consider skip having the SQL query part of this script, and maybe have the script only open the tunnel? Perhaps the reason is that you don't want to clog up long running db connections too long?

**Comment by busla** [comment]
the script runs db-proxy.sh in the background to create the tunnel, which can be used for tunnel-only purposes.

The query is optional. The allowed options (mutually exclusive)  are `-q [string]` and `-p` (psql console).


Did I understand your question correctly 😄

**Review by pshomov — APPROVED** [review]
LGTM

**Review by gudjong — APPROVED** [review]
Not sure why Kolibri Justice League needs to review this, but it looks fine.

**Pull request closed without merging**
