### PR TITLE
chore(core): Monorepo upgrade

### PR DESCRIPTION
**Pull request by saevarma**
# Upgrade monorepo dependencies

## What

This PR includes major version upgrades our most important packages:
- Jest 27
- Nx 13
- NestJS 8
- NextJS 12
- RxJS 7
- Sequelize 6
- Sequelize-typescript 2
- Webpack 5

See further description in [Notion](https://www.notion.so/Nx-13-0-1-a77cd802539e468596da6265700ff3cf)

## Why

The repo was falling behind on version upgrades. So it was necessary to upgrade our most important dependencies.

## Screenshots / Gifs

Attach Screenshots / Gifs to help reviewers understand the scope of the pull request

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

### CODE REVIEW

**Comment by obmagnusson** [comment]
Seems the application system is broken on the feature branch. The "Cannot set properties of undefined (setting '')" error is showing up in console. We encountered the same error  when including the Kennitala lib earlier this year. Was fixed [here](https://github.com/HermannBjorgvin/Kennitala/pull/23 by @eirikurn.  Don't know if it is related.

**Comment by saevarma** [comment]
> Seems the application system is broken on the feature branch. The "Cannot set properties of undefined (setting '')" error is showing up in console. We encountered the same error when including the Kennitala lib earlier this year. Was fixed [here]([HermannBjorgvin/Kennitala#23](https://github.com/HermannBjorgvin/Kennitala/pull/23) by @eirikurn. Don't know if it is related.

Okay, thanks for the info. I will look into that.

**Comment by disaerna** [comment]
Finanace status in service portal is not working. 
* ReferenceError: Buffer is not defined - when first loaded 
* Uncaught (in promise) ReferenceError: Cannot access 'H' before initialization - when revisited

**Comment by saevarma** [comment]
> Seems the application system is broken on the feature branch. The "Cannot set properties of undefined (setting '')" error is showing up in console. We encountered the same error when including the Kennitala lib earlier this year. Was fixed [here]([HermannBjorgvin/Kennitala#23](https://github.com/HermannBjorgvin/Kennitala/pull/23) by @eirikurn. Don't know if it is related.

Okay, thanks for the info. I will look into that.

> 

Yes, fix works locally. Trying to update and test on the feature branch.

**Pull request merged**
