### PR TITLE
Change Digital Iceland link 

### PR DESCRIPTION
**Pull request by koddsson**
Not sure if this is the right link but pretty sure that reddit.com is the wrong link 😅

### CODE REVIEW

**Comment by DavidBachmann** [comment]
@eirikurn https://github.com/island-is/island.is/commit/bfc339f873cb9c8e67a16c9e2259b9b9e6827981#diff-04c6e90faac2675aa89e2176d2eec7d8R11

:'D

**Comment by eirikurn** [comment]
Whoops! I updated your branch with this url: https://stafraent.island.is/

Thanks! 😅

**Comment by koddsson** [comment]
Thank all ❤️

**Comment by sindrig** [comment]
@koddsson I've merged #805, care to rebase?

**Review by pshomov — DISMISSED** [review]
LGTM

**Comment by pshomov** [comment]
@arividar do we have a special prize for external contributor Nr. 1? 🎉

**Comment by koddsson** [comment]
Not sure why CI isn't running now @sindrig 😬

**Comment by sindrig** [comment]
Well.. beats me. I created #921 (island-is branch) and #922 (forked) and CI ran fine. I wonder if it has anything to do with you closing the PR and then pushing. Although I've tried to reproduce that as well.

If you're feeling adventurous you can try squashing the commits and see if GitHub is happy with that. I have no way (that I know of) to manually kick of the CI.

**Comment by sindrig** [comment]
Sadly, I can't select your branch, so although #923 is nice it doesn't help with this particular issue :(
image

**Comment by koddsson** [comment]
Maybe we can just merge this in without CI since this isn't a code change and y'all can figure out CI separately?

**Review by sindrig — APPROVED** [review]

**Comment by sindrig** [comment]
Thanks @koddsson :tada:

**Pull request merged**
