### PR TITLE
chore(service-portal): swap auth finance

### PR DESCRIPTION
**Pull request by thordurhhh**
## What

Swap basic auth for openid auth in finance section.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by Valur — APPROVED** [review]

**Comment by osk** [comment]
We should also clean up `FINANCE_USER` and `FINANCE_PASS` from `yaml` files in `charts/`.

**Review by saevarma — APPROVED** [review]
Approved.
But you should consider to add our Audit log service, as this resolver is getting user specific financial data.

**Comment by thordurhhh** [comment]
> Approved.
> But you should consider to add our Audit log service, as this resolver is getting user specific financial data.

Yes! Good call, that will be the next step.

**Review by pshomov — APPROVED** [review]
LGTM

**Pull request merged**
