### PR TITLE
fix(service-portal): only fetch the organization we need

### PR DESCRIPTION
**Pull request by Valur**
## What

Only fetch specific organization by slug when needed instead of fetching all 230+ every time in both intro and footer

## Why

improve performance

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

### CODE REVIEW

**Review by thordurhhh — APPROVED** [review]
nice!

**Review by kksteini — APPROVED** [review]
CODEOWNER files LGTM

**Review by obmagnusson — APPROVED** [review]
Codeowned file LGTM

**Review by baering — APPROVED** [review]
Core files LGTM

**Pull request merged**
