### PR TITLE
fix(service-portal): fix for disabled link on closedDate + few text fixes

### PR DESCRIPTION
**Pull request by albinagu**
Fix for disabled 'Afskrá meðmæli' link when list is closed
Fix for mobile menu closing instead of expanding with children items

List open:
Screenshot 2021-07-22 at 09 59 31

List closed:
Screenshot 2021-07-22 at 10 01 06

MobileMenu alwaysExpanded:
Screenshot 2021-07-22 at 13 12 36

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

### CODE REVIEW

**Review by kksteini — APPROVED** [review]
LGTM

**Comment by thordurhhh** [comment]
With these changes it seems like there would be no chance for the user to get to the root of a menu item within the mobile menu.

Example *Mínar upplýsingar*:

Screenshot 2021-07-22 at 13 31 49

**Review by thordurhhh — APPROVED** [review]
LGTM 👍

**Comment by thordurhhh** [comment]
I have added a ticket for the designer to take a look at a redesign for the service-portal mobile menu when the summer holidays are finished.

**Comment by albinagu** [comment]
> I have added a ticket for the designer to take a look at a redesign for the service-portal mobile menu when the summer holidays are finished.

Great! Thanks!

**Pull request merged**
