### PR TITLE
island.is / tab keyboard

### PR DESCRIPTION
**Pull request by barabrian**
# Tab keyboard

https://app.asana.com/0/1183498341031105/1195547281923279

## What

Fix class names on keyboard navigation

## Why

Keyboard navigation was not updating selected tab class name

## Screenshots / Gifs

tab-focus-keyboard

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against master before asking for a review

### CODE REVIEW

**Comment by DavidBachmann** [comment]
Cool.
Can you also add a visible indicator that the currently selected tab is focused? There's no way to see if I can press the arrow keys or not.

**Comment by barabrian** [comment]
> Cool.
> Can you also add a visible indicator that the currently selected tab is focused? There's no way to see if I can press the arrow keys or not.

good point! you think we should go with the same focus as text buttons?
image
maybe to-much ?

**Comment by DavidBachmann** [comment]
I edited my comment to suggest FocusableBox

**Review by DavidBachmann — APPROVED** [review]
LGTM

**Pull request merged**
