### PR TITLE
Import DocumentBuilder from nestjs/swagger to fix a broken master

### PR DESCRIPTION
**Pull request by oddsson**

### CODE REVIEW

**Review by eirikurn — DISMISSED** [review]
LGTM. Are the other format issues fixed?

**Comment by oddsson** [comment]
They are now, let's see if all checks pass now...

**Comment by oddsson** [comment]
@unnarb, this task is failing because of eslint rules that are failing (https://github.com/island-is/island.is/pull/829/checks?check_run_id=1114873442). Could you please take a look and fix them, I believe you wrote this code, right? ☺️ 🙏

**Review by gudjong — APPROVED** [review]

**Comment by unnarb** [comment]
@oddsson we are reverting our changes. It was intended to merge to another feature branch. 
Sorry!

**Pull request merged**
