### PR TITLE
Revert "Feature/api catalog (#1405)"

### PR DESCRIPTION
**Pull request by sindrig**
This reverts commit a82abd0f737d765a46732f6d78fcf78bfe0260a8.

The PR https://github.com/island-is/island.is/pull/1405 was merged under pressure and has since a) not been accepted by the CODEOWNERS that were bypassed anb b) was not able to be demoed this morning. Hence, it feels right to me to go through code review again.

### CODE REVIEW

**Review by darrikonn — APPROVED** [review]

**Comment by darrikonn** [comment]
Would be nice to get the reason for reverting in the description

**Comment by sindrig** [comment]
> Would be nice to get the reason for reverting in the description

Done

**Review by saevarma — APPROVED** [review]
@vigfusg moved the demo until tomorrow @15.30
I'm not sure if we can manage to refactor the review comments from #1405  before the demo, could we look into keep this in a separate branch to deploy to dev? Any other solution how we could make this demoable but keep sperate from the master?

Also the api-catalogue will become a part of the web (ytri vefurinn) so the plan is to refactor this as part of the work to merge it into the web project.

**Review by DavidBachmann — APPROVED** [review]

**Comment by darrikonn** [comment]
Can't you just create a release candidate and deploy it to staging for the demo (using the git tags that @sindrig implemented)?

^ the best way to avoid merging not-ready-code to master

**Comment by saevarma** [comment]
> Can't you just create a release candidate and deploy it to staging for the demo (using the git tags that @sindrig implemented)?
> 
> ^ the best way to avoid merging not-ready-code to master

@sindrig  any info on those git tags for this approach?

**Comment by sindrig** [comment]
> > Can't you just create a release candidate and deploy it to staging for the demo (using the git tags that @sindrig implemented)?
> > ^ the best way to avoid merging not-ready-code to master
> 
> @sindrig any info on those git tags for this approach?

Sure - you can tag and push your commit with the prefix `docker-build-`, e.g. `docker-build-viskuausan-v1`. That will then build containers of your application that we can deploy using spinnaker.

**Pull request merged**
