### PR TITLE
Unblock main

### PR DESCRIPTION
**Pull request by darrikonn**
# Fix main

## What

Fix main

## Why

I broke it (shame)

### CODE REVIEW

**Review by barabrian — APPROVED** [review]
LGTM!

**Comment by jeremybarbet** [comment]
Got also this when running the `application-system-api`

```bash
ERROR in /Users/jeremy/www/island.is/libs/application/templates/driving-license/src/forms/application.ts(144,17):
TS2532: Object is possibly 'undefined'.
ERROR in /Users/jeremy/www/island.is/libs/application/templates/driving-license/src/forms/application.ts(144,39):
TS2339: Property 'fullName' does not exist on type 'string | number | boolean | object'.
  Property 'fullName' does not exist on type 'string'.
ERROR in /Users/jeremy/www/island.is/libs/shared/form-fields/src/lib/CheckboxController/CheckboxController.tsx(76,19):
TS2322: Type 'ReactNode' is not assignable to type 'string | undefined'.
  Type 'null' is not assignable to type 'string | undefined'.
ERROR in /Users/jeremy/www/island.is/libs/shared/form-fields/src/lib/CheckboxController/CheckboxController.tsx(79,19):
TS2322: Type 'ReactNode' is not assignable to type 'string | undefined'.
  Type 'null' is not assignable to type 'string | undefined'.
Version: typescript 3.9.7
Time: 36230ms
```

**Review by barabrian — APPROVED** [review]

**Comment by jeremybarbet** [comment]
On another note, I also believe you need to define at least an `id` for a new field in the AS. Otherwise, you won't be able to define a `dataSchema` for this specific field

**Comment by darrikonn** [comment]
reverted the changes on main and will continue in another PR

**Pull request closed without merging**
