### PR TITLE
feat(service-portal): Configure access control on all service portal modules

### PR DESCRIPTION
**Pull request by eirikurn**
## What

Add scope checks to all service portal modules and associated API resolvers/controllers.

## Why

To allow us to release the delegation system. When users are able to get an access token in another's name, we want to make sure that access token can only be used for authorised services. This means that all of our services need to check on some scope in addition to the token audience.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] ~I have made corresponding changes to the documentation~
- [x] My changes generate no new warnings
- [ ] ~I have added tests that prove my fix is effective or that my feature works~
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review
- [ ] Verify that our clients still work.
- [ ] Add scope migrations or create them in staging/production.
- [x] Review remaining API domains, check if some scope checks are missing.

### CODE REVIEW

**Review by valurefugl — APPROVED** [review]

**Review by JuliusGG — APPROVED** [review]

**Review by thordurhhh — APPROVED** [review]
Nice!

LGTM

**Review by arnorhs — APPROVED** [review]
LGTM

**Review by darrikonn — APPROVED** [review]

**Review by miamiultras — APPROVED** [review]

**Review by Rikkiabb — APPROVED** [review]
🚢

**Comment by eirikurn** [comment]
Fyi, the CI failure is some strange false negative. Always fails with a node16 issue the first build after push then succeeds when I do "re-run all jobs". Will monitor main.

**Pull request merged**
