### PR TITLE
fix(web): Reduce use of `React.FC` type on components accepting no children

### PR DESCRIPTION
**Pull request by maranomynet**
## What

A bit of house-keeping, skipping use of `React.FC` in favor of simple argument typing.

## Why

Components typed so that they accept children, yet don't display them, are incorrectly typed and confusing for developers.

Faster (TS error) feedback === less wasted time/effort.

Also: Here's rationale from the CRA maintainers for why `React.FC` is generally not very useful: https://github.com/facebook/create-react-app/pull/8177#issue-353062710

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [x] My changes generate no new warnings
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by eirikurn — APPROVED** [review]
👍

**Comment by maranomynet** [comment]
Just a bit of house-keeping. Not doing them all this time around, as there are soo many.

**Review by atligudl — APPROVED** [review]

**Review by barabrian — APPROVED** [review]
Nice! 😄

**Review by Ingimarsson — APPROVED** [review]
LGTM

**Pull request merged**
