### PR TITLE
feat(half-old-age-pension): apply for half old-age pension

### PR DESCRIPTION
**Pull request by karenbjorg**
## What

added half old-age pension option to types of old-age pension application
http://localhost:4242/umsoknir/ellilifeyrir/ 

## Why

for applicants to apply for half old-age pension at Social Insurance Administration (TR).
same flow as old-age pension but they need to answer if they are self employed or have an employee (if so register them)

### Gervimenn that should work for this application
María ÞÍ Lulic - 0111439

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by ylfahfa — APPROVED** [review]
lgtm

**Comment by lodmfjord** [comment]
I am going to revert my hack and then approve this. Wait :)

**Comment by lodmfjord** [comment]
Waiting for this to merge:
https://github.com/island-is/island.is/pull/13373

which has the fix for code generation this pr needs.

**Review by lodmfjord — APPROVED** [review]
LGTM

**Pull request merged**
