### PR TITLE
fix(core): Fix NX caching issues during codegen

### PR DESCRIPTION
**Pull request by eirikurn**
## What

These projects had incorrectly configured codegen outputs.

## Why

So we can trust the NX cache to speed up some builds.

## Summary by CodeRabbit

- **New Features**
  - Added new output files for GraphQL code generation in web applications.
  - Expanded output configuration for generated TypeScript files in client projects.

- **Refactor**
  - Renamed generated files from `graphql.ts` to `schema.ts` in multiple modules.
  - Updated import paths for GraphQL queries in various components to reflect new file names.

- **Chores**
  - Adjusted the structure and settings in project configurations to better manage file outputs.

### CODE REVIEW

**Review by birkirkristmunds — APPROVED** [review]
LGTM

**Review by thorkellmani — APPROVED** [review]
LGTM (hugsmiðjan)

**Review by Toti91 — APPROVED** [review]
LGTM

**Review by saevarma — APPROVED** [review]

**Review by snaerseljan — APPROVED** [review]
Nice work

**Pull request merged**
