### PR TITLE
feat(web): KAM-2057: header and footer for thjodskjalasafnid

### PR DESCRIPTION
**Pull request by karlarnar**
# Header and footer for þjóðskjalasafnið

https://veflausnir.atlassian.net/browse/KAM-2057

## What

Custom header for þjóðskjalasafnið

## Why

Specify why you need to achieve this

## Screenshots / Gifs

image
image

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Comment by andes-it** [comment]
This PR's had a 15-day siesta. Lost its spark, did it? It's making an exit in 5 days unless the stale label disappears.

**Comment by karlarnar** [comment]
closed due to using the default header instead

**Pull request closed without merging**
