### PR TITLE
Updating to latest 12.x nodejs version in dockerfile.

### PR DESCRIPTION
**Pull request by Addips**
## What

Updating the dockerfile to create base images for containers in the latest 12.x version

## Why

We were experience a bug in build nextjs app for Viskuausan which required a higher node version to solve

`Error: EFAULT: bad address in system call argument, read
    at Object.readSync (fs.js:524:3)
    at tryReadSync (fs.js:349:20)
    at Object.readFileSync (fs.js:378:19)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1182:22)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at loadComponents (/webapp/node_modules/next/dist/next-server/server/load-components.js:1:945)
    at Server.findPageComponents (/webapp/node_modules/next/dist/next-server/server/next-server.js:54:189)
    at Server.renderToHTML (/webapp/node_modules/next/dist/next-server/server/next-server.js:102:198)
    at Server.render (/webapp/node_modules/next/dist/next-server/server/next-server.js:52:247)
    at Object.fn (/webapp/node_modules/next/dist/next-server/server/next-server.js:37:275)
    at Object.fn (/webapp/node_modules/next/dist/next-server/server/router.js:11:385)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Router.execute (/webapp/node_modules/next/dist/next-server/server/router.js:23:67) {
  errno: -14,
  syscall: 'read',
  code: 'EFAULT'`

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against master before asking for a review

### CODE REVIEW

**Comment by pshomov** [comment]
Did upgrading the nodejs version help with the bug? The real issue with nextjs was fixed by @sindrig and his task force but it is not a bad idea to bump nodejs version. I think you should bump all versions of nodejs in that Dockerfile though just to make sure the build nodejs and the runtime one are one and the same.

**Comment by Addips** [comment]
> Did upgrading the nodejs version help with the bug? The real issue with nextjs was fixed by @sindrig and his task force but it is not a bad idea to bump nodejs version. I think you should bump all versions of nodejs in that Dockerfile though just to make sure the build nodejs and the runtime one are one and the same.

I believe so, we were getting a different error from the OOM before the node version was updated, but I can't be sure. Will updated all of the node versions in the docker file :)

**Comment by Addips** [comment]
> ```
> We were experience a bug in build nextjs app 
> ```
> 
> Care to share the bug with us?

Error: EFAULT: bad address in system call argument, read
    at Object.readSync (fs.js:524:3)
    at tryReadSync (fs.js:349:20)
    at Object.readFileSync (fs.js:378:19)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1182:22)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at loadComponents (/webapp/node_modules/next/dist/next-server/server/load-components.js:1:945)
    at Server.findPageComponents (/webapp/node_modules/next/dist/next-server/server/next-server.js:54:189)
    at Server.renderToHTML (/webapp/node_modules/next/dist/next-server/server/next-server.js:102:198)
    at Server.render (/webapp/node_modules/next/dist/next-server/server/next-server.js:52:247)
    at Object.fn (/webapp/node_modules/next/dist/next-server/server/next-server.js:37:275)
    at Object.fn (/webapp/node_modules/next/dist/next-server/server/router.js:11:385)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Router.execute (/webapp/node_modules/next/dist/next-server/server/router.js:23:67) {
  errno: -14,
  syscall: 'read',
  code: 'EFAULT'

Is what I know, Andri was investigating :)

**Review by pshomov — APPROVED** [review]
LGTM

**Pull request merged**
