### PR TITLE
chore: throw eslint error for dot import

### PR DESCRIPTION
**Pull request by jeremybarbet**
## What

- Not recommended to use dot import and can cause unexpected errors. Better to restrict them and force the import for the specific file

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Formatting passes locally with my changes
- [ ] I have rebased against main before asking for a review

### CODE REVIEW

**Review by stefanhar — APPROVED** [review]
LGTM

**Review by pshomov — APPROVED** [review]
LGTM

**Review by dd-sdang — APPROVED** [review]
Looks good

**Review by sindrig — APPROVED** [review]

**Review by darrikonn — APPROVED** [review]

**Review by stefanhar — APPROVED** [review]
SLGTM

**Review by saevarma — APPROVED** [review]
LGTM

**Review by dd-sdang — APPROVED** [review]

**Pull request merged**
