### PR TITLE
Remove apps/adgerdir project (finally)

### PR DESCRIPTION
**Pull request by stjanilofts**
## What

Removes apps/adgerdir which is not used and will not ever be used. Parts of it that will be used have already been moved to apps/web.

## Why

Should have been removed already. Better late than never.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Formatting passes locally with my changes
- [x] I have rebased against main before asking for a review

### CODE REVIEW

**Review by siggakogk — APPROVED** [review]
niiice 🎊

**Review by pshomov — APPROVED** [review]
👍🏻

**Comment by jeremybarbet** [comment]
🎉

**Review by arnifreyrs — COMMENTED** [review]
Awesome!

**Pull request merged**
